### ISSUE TITLE
bumphunter DMR analysis 

### ISSUE THREAD

**Issue by brianchengithub** [FoxoTech/methylize#2]
Mimic 'bumphunter' package: 
https://github.com/rafalab/bumphunter

Citation: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3304533/

see `bumphunter` folder for `R` and python scripts demonstrating how this is done. Needs a cleanup and API to be complete.

**Comment by marcmaxson** [comment]
Instead of bumpHunter, version 0.9.8 features the `combined-pvalues` library by Brent Pedersen (https://github.com/brentp) that does the same thing and is written in python, not R. His package is CLI with no real API so I had to retool parts of it and call the functions but not his use "pipeline" function.
